include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Code Style (helps with consistency)
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_single_quotes
    - require_trailing_commas
    - always_declare_return_types
    - directives_ordering

    # Error Prevention (catches bugs early)
    - avoid_print  # Use debugPrint() instead
    - cancel_subscriptions
    - close_sinks
    - unawaited_futures
    - use_build_context_synchronously  # Critical for async operations

    # Code Quality (clean code)
    - prefer_is_empty
    - prefer_is_not_empty
    - use_key_in_widget_constructors
    - sized_box_for_whitespace
    - avoid_unnecessary_containers
    - unnecessary_null_checks

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "lib/firebase_options.dart"
    - "build/**"
    - ".dart_tool/**"

  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    todo: ignore  # Don't warn about TODOs - useful for solo dev
    unused_local_variable: warning  # Warning instead of error

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
