targets:
  $default:
    builders:
      drift_dev:
        options:
          generate_connect_constructor: false
          skip_verification_code: false
        generate_for:
          exclude:
            - lib/features/**/providers/**
            - lib/features/**/widgets/**
            - lib/**/*_provider.dart
            - test/**
